// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "hacker":return img`
....................
....................
....................
....................
....................
........11111.......
.......1111111......
......1111ddd11.....
.....1111dddd11.....
.....1111ddfd1......
......11ddddd.......
......111dddd.......
.......1ddddd.......
.........dd.........
......ffffff........
.....ffffffff.......
....fffffffff.......
....fffffffff.......
...ffffffffff.......
......fffffff.......
......fffffff.......
......fffffff.......
......fffffff.......
......fffffff.......
......ffffffd.......
......fffddf........
......ffffff........
.......fffff........
.......fffff........
........ffff........
........ffff........
........ffff........
........ffff........
........ffff........
........ffff........
........ffff........
........ffff........
........ffff........
.........ee.........
.........eee........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
